############ ENVIRONMENT SETTINGS ############
APP_VERSION = "1.0 beta"
RELEASE_DT = "2011-10"
DISP_LANG = "Español(ESP), English(ENG)"

############ RUNTIME SETTINGS ############
GRID_COL_WIDTH_DT = 100
CURRENT_DATE = Time.now.strftime("%Y-%m-%d")

############ LANGUAGE INDEPENDANT ############
ERR_LOC_VAL_NAME = "/validation.rb(checkValidName)"
ERR_LOC_VAL_ADDRESS = "/validation.rb(checkValidAddress)"
ERR_LOC_VAL_PHONE = "/validation.rb(checkValidPhone)"
ERR_LOC_VAL_DATE = "/validation.rb(checkValidDate)"
ERR_LOC_VAL_INT = "/validation.rb(checkValidInt)"
ERR_LOC_VAL_FLOAT = "/validation.rb(checkValidFloat)"
ERR_LOC_VAL_PRICE = "/validation.rb(checkValidPrice)"
ERR_LOC_VAL_GUI_INT = "/validation.rb(guiCheckValidInt)"
ERR_LOC_VAL_GUI_FLOAT = "/validation.rb(guiCheckValidFloat)"
ERR_LOC_VAL_GUI_STR = "/validation.rb(guiCheckValidString)"
ERR_LOC_CUST_MOD = "/customer.rb(modify)"
ERR_LOC_PROD_MOD = "/product.rb(modify)"
ERR_LOC_ORD_CRE = "/order.rb(create)"
ERR_LOC_ORD_MOD = "/order.rb(modify)"
ERR_LOC_ORD_UPDST = "/order.rb(updateStatus)"
ERR_LOC_INICNF_SLFCN = "/init_config.rb(setLogFileCompleteName)"
ERR_LOC_INICNF_GDBCN = "/init_config.rb(getDBCompleteName)"
ERR_LOC_BILL_VLDST = "/billing.rb(checkValidStatus)"
ERR_LOC_PAR_LANG = "/params.rb"
ERR_INVALID_LANG = "#{APP_LANG} is not a supported language. Please go to config.rb and select a valid choice."
LBL_ERROR = "ERROR"

############ LANGUAGE DEPENDANT ############
case APP_LANG
	when "ESP"
		############ GENERALES ############
		APP_NAME = "Gestor de PyMEs"
		PEND_STATUS = "PENDIENTE"
		CANC_STATUS = "CANCELADA"
		COMP_STATUS = "ENTREGADA"
		############ ETIQUETAS ############
		LBL_CUST = "CLIENTES"
		LBL_PROD = "PRODUCTOS"
		LBL_ORD  = "ORDENES"
		LBL_ABOUT = "ACERCA DE..."
		LBL_ID = "ID"
		LBL_NAME = "NOMBRE"
		LBL_ADDRESS = "DIRECCION"
		LBL_PHONE = "TELEFONO"
		LBL_LASTORDERDT = "ULT ORDEN"
		LBL_CREATEDDT = "CREACION"
		LBL_LASTUPDATEDDT = "ULT MODIF"
		LBL_PRCLSTUPDDT = "PR ULTMOD"
		LBL_STKLSTUPDDT = "ST ULTMOD"
		LBL_PRICE = "PRECIO"
		LBL_UNITPRC = "PRECIO UN."
		LBL_STOCK = "STOCK"
		LBL_STOCK_TO_ADD = "STOCK A AGREGAR"
		LBL_STATUS = "ESTADO"
		LBL_CUSTNAME = "CLIENTE"
		LBL_INCOME = "MONTO"
		LBL_ORDERDT = "CREADA"
		LBL_ESTDELIVERYDT = "ENTR. EST"
		LBL_DELIVERYDT = "ENTREGADA"
		LBL_PRODNAME = "PRODUCTO"
		LBL_AMOUNT = "CANTIDAD"
		LBL_RANGE = "PERIODO"
		LBL_DATE = "FECHA"
		LBL_DAY = "DIA"
		LBL_MONTH = "MES"
		LBL_YEAR = "AÑO"
		LBL_DAY_STA = "DIA INI"
		LBL_MONTH_STA = "MES INI"
		LBL_YEAR_STA = "AÑO INI"
		LBL_DAY_STP = "DIA FIN"
		LBL_MONTH_STP = "MES FIN"
		LBL_YEAR_STP = "AÑO FIN"
		LBL_ADD = "AGREGAR"
		LBL_REMOVE = "ELIMINAR"
		LBL_MOD_STK = "MODIFICAR STOCK"
		LBL_ABOUT_EMAIL = "EMAIL"
		LBL_ABOUT_BLOG = "BLOG"
		LBL_ABOUT_GITHUB = "GITHUB"
		LBL_ABOUT_LINKED = "LINKED-IN"
		LBL_BILL_CLIENT = "EMPRESA"
		LBL_BILL_CUSTDET = "DATOS DEL CLIENTE"
		LBL_BILL_ORDDET = "DATOS DE LA ORDEN"
		LBL_BILL_SUBTOTAL = "SUBTOTAL"
		LBL_BILL_TOTAL = "TOTAL"
		LBL_BILL_ORDID = "Orden #"
		LBL_BILL = "Factura"
		LBL_CUIT = "CUIT"
		LBL_OK = "CONFIRMACION"
		############ BOTONES ############
		BTN_RETR_ALL = "Listar todos"
		BTN_RETR_DET = "Mostrar detalles"
		BTN_RETR_OOS = "Listar s/stock"
		BTN_ADD = "Agregar"
		BTN_CRE = "Crear"
		BTN_MOD = "Modificar"
		BTN_REM = "Eliminar"
		BTN_FIND = "Buscar"
		BTN_ADD_STO = "Agregar stock"
		BTN_OK = "Aceptar"
		BTN_CANCEL = "Cancelar"
		BTN_COMP_ST = "Completar(ST)"
		BTN_CANC_ST = "Cancelar(ST)"
		BTN_RETR_DAY = "Listar dia"
		BTN_RETR_MNTH = "Listar mes"
		BTN_RETR_YEAR = "Listar año"
		BTN_RETR_RNG = "Listar periodo"
		BTN_RETR_DT = "Listar fecha"
		BTN_RETR_CUST = "Buscar cliente"
		BTN_RETR_PROD = "Buscar producto"
		BTN_GEN_BILL = "Generar factura"
		############ NOMBRES DE DIALOGOS ############
		ADD_CUST_DIALOG = "Agregar Cliente"
		MOD_CUST_DIALOG = "Editar Cliente"
		ADD_PROD_DIALOG = "Agregar Producto"
		MOD_PROD_DIALOG = "Editar Producto"
		ADD_STOCK_DIALOG = "Agregar Stock"
		CRE_ORD_DIALOG = "Crear Orden"
		INPUT_DATE_DIALOG = "Ingresar Fecha"
		MOD_ORD_DIALOG = "Modificar Orden"
		MOD_ORDST_DIALOG = "Modificar Estado de Orden"
		DEL_CUST_DIALOG = "Eliminar Cliente"
		DEL_PROD_DIALOG = "Eliminar Producto"
		############ MENSAJES DE ERROR Y CONFIRMACION ############
		ERR_PROD_NOT_FND = "El producto no existe en la tabla de productos. Producto #:"
		ERR_PROD_INV_PRC = "Precio invalido en la tabla de productos. Producto #:"
		ERR_PROD_INV_STK = "Stock invalido en la tabla de productos. Producto #:"
		ERR_PROD_OUT_STK = "No se puede crear la orden ya que el/los producto(s) no tienen suficiente Stock. Producto #(s):"
		ERR_CANT_MOD_ORD = "No se puede modificar una orden cuyo estado es #{CANC_STATUS} o #{COMP_STATUS}. Orden #:"
		ERR_CANT_BILL_ORD = "No se puede generar factura para una orden cuyo estado es #{CANC_STATUS}. Orden #:"
		ERR_ORD_DUPL_PROD = "El producto ya existe en la orden. Revise la lista"
		ERR_LOG_FILE_NAME = "No se pudo generar el nombre del archivo de logs"
		ERR_DB_FILE_NAME = "No se pudo generar el nombre del archivo de base de datos"
		ERR_GUI_EMPTY_ROW = "La fila seleccionada esta vacia"
		ERR_GUI_NO_ROW_SEL = "No hay ninguna fila seleccionada"
		ERR_GUI_CNT_EDT_MLT_RW = "No se pueden modificar multiples lineas\nSeleccione solo una"
		ERR_GUI_CNT_SHW_MLT_DET = "No se pueden mostrar detalles de multiples ordenes\nSeleccione solo una"
		ERR_GUI_CNT_GEN_MLT_BILL = "No se pueden generar facturas para multiples ordenes.\nSeleccione solo una"
		ERR_GUI_NO_STR_INPUT = "No se ha ingresado ninguna busqueda"
		ERR_GUI_EMPTY_CUST = "Se debe ingresar un cliente"
		ERR_GUI_EMPTY_PROD = "Se debe seleccionar al menos un producto"
		ERR_INVALID_NAME = "El nombre ingresado solo puede contener letras y numeros"
		ERR_INVALID_ADDRESS = "La direccion ingresada debe contener (solo) letras y numeros"
		ERR_INVALID_PHONE = "El telefono ingresado debe contener solo numeros separados por guiones y el formato debe ser XXXX-XXXX o XX-XXXX-XXXX"
		ERR_INVALID_DATE = "La fecha ingresada no existe de acuerdo al calendario"
		ERR_INVALID_MONTH = "El mes ingresado debe estar entre 1 y 12"
		ERR_INVALID_PAST_DATE = "La fecha ingresada no puede ser previa al dia corriente"
		ERR_INVALID_DATE_FMT = "La fecha ingresada debe tener el siguiente formato AAAA-MM-DD"
		ERR_INVALID_DATE_LEN = "La fecha ingresada debe ser de diez caracteres(AAAA-MM-DD)"
		ERR_INVALID_DATE_CHAR = "La fecha ingresada solo puede contener numeros separados por guiones"
		ERR_INVALID_INT = "El numero ingresado debe ser entero"
		ERR_INVALID_FLOAT = "El numero ingresado debe ser un entero o un decimal separado por un punto"
		ERR_INVALID_PRICE = "El precio debe ser mayor a cero"
		ERR_INVALID_ACTION = "La accion seleccionada es invalida"
		ERR_INVALID_STR = "El valor ingresado no es valido. Solo puede contener letras, numeros, espacios, guiones medios y bajos"
		OK_BILL_GENERATED = "La factura fue generada correctamente para la Orden #: "
		WRN_MOD_ORDST_CONF = "Esta seguro de que quiere modificar el estado de la orden?"
		WRN_DEL_CUST_CONF = "Esta seguro de que quiere eliminar el cliente?"
		WRN_DEL_PROD_CONF = "Esta seguro de que quiere eliminar el producto?"
		############ TEXTO ############
		TXT_ABOUT_HEADER = "Esta aplicacion esta pensada como una herramienta para gestionar pequeñas empresas. Ofrece velocidad, simplicidad y todas las funcionalidades requeridas para manejar clientes, productos, ordenes y facturacion.\n\nAl estar en constante desarrollo, permite ajustar la aplicacion a las necesidades particulares del cliente. Si usted require una aplicacion a medida, no dude en contactarse por alguno de los medios provistos a continuacion.\n\nDesde ya muchas gracias por utilizar este producto."
		TXT_ABOUT_APPINFO = "VERSION:\t#{APP_VERSION}\nRELEASED:\t#{RELEASE_DT}"
		TXT_BILL_ABOUT = "Factura generada en forma automatica por '#{APP_NAME}' version #{APP_VERSION} #{RELEASE_DT}"
		TXT_BILL_CONTACT = "Contacto: alejandro.riedel@gmail.com / 15-6041-4327"
	when "ENG"

	else
		raise RuntimeError, "#{ERR_INVALID_LANG}. Supported languages: #{DISP_LANG}", ERR_LOC_PAR_LANG
end
